#Format: RequestClass=ResponseClass:field1=field1Response,field2=field2Response

CustomerProfileUpdateRequest=CustomerProfileUpdateResponse:name=customer.name

CustomerProfileGetResponse=CustomerProfileGetResponse:name=name

CustomerAccountsGetResponse=CustomerAccountsGetResponse:balance=balance